# from micropython import const  # type: ignore
from adafruit_blinka import Enum as Enum

HA_MQTT_PREFIX = "homeassistant"

CONFIG_AVAILABILITY = "avty"
CONFIG_COMMAND_TOPIC = "cmd_t"
CONFIG_CONNECTIONS = "cns"
CONFIG_DEVICE = "dev"
CONFIG_ENABLED_BY_DEFAULT = "en"
CONFIG_ENCODING = "e"
CONFIG_FORCE_UPDATE = "force_update"
CONFIG_HARDWARE = "hw"
CONFIG_IDENTIFIERS = "ids"
CONFIG_NAME = "name"
CONFIG_DEVICE_CLASS = "dev_cla"
CONFIG_ENTITY_CATEGORY = "ent_cat"
CONFIG_EXPIRE_AFTER = "expire_after"
CONFIG_ICON = "ic"
CONFIG_MANUFACTURER = "mf"
CONFIG_OPTIMISTIC = "opt"
CONFIG_PAYLOAD_OFF = "pl_off"
CONFIG_PAYLOAD_ON = "pl_on"
CONFIG_RETAIN = "ret"
CONFIG_STATE_TOPIC = "stat_t"
CONFIG_TOPIC = "t"
CONFIG_UNIQUE_ID = "unique_id"
