default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: detect-private-key

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files", "--skip-gitignore"]

  # - repo: https://github.com/python-poetry/poetry
  #   rev: '1.7.0'  # add version here
  #   hooks:
  #   - id: poetry-lock
  #   - id: poetry-check
  #   - id: poetry-export
  #     args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
  #   - id: poetry-install
