[tool.poetry]
name = "minihass"
version = "0.1.0"
description = "MQTT Home Assistant Device in CircuitPython"
authors = ["Adam Schumacher <adam@genericor.com>"]
license = "MIT License"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.10"
adafruit-circuitpython-minimqtt = "^7.4.3"
schema = "^0.7.5"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "*"
sphinx-rtd-theme = "^1.3.0"

[tool.poetry.group.test.dependencies]
tox = "*"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]