[tool.poetry]
name = "minihass"
version = "0.1.0"
description = "MQTT Home Assistant Device in CircuitPython"
authors = ["Adam Schumacher <adam@genericor.com>"]
license = "MIT License"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"
adafruit-circuitpython-minimqtt = "^7.4.3"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "*"
sphinx-rtd-theme = "^1.3.0"

[tool.poetry.group.test.dependencies]
tox = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
