name: "Docs"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    # - name: Install Poetry
    #   uses: snok/install-poetry@v1
    #   with:
    #     virtualenvs-create: true
    #     virtualenvs-in-project: true
    - name: Install project and dependencies
      run: |
        pip install -r requirements.txt
        pip install -r optional_requirements.txt
        pip install .
    - name: build docs
      run: |
        cd docs
        make html
        cd build/html
        touch CNAME
        echo "circuitpython-minihass.ensmarten.ing" > CNAME
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
