name: Tests

on: pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install project and dependencies
      run: poetry install --with docs --no-interaction
    - name: Run tests and collect coverage
      id: pytest
      run: |
        . .venv/bin/activate
        pytest --cov=minihass --cov-report=xml
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v3
