name: Tests

on: [push, pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install project and dependencies
      run: poetry install --with docs --no-interaction
    - name: Run tests and collect coverage
      id: pytest
      run: |
        . .venv/bin/activate
        pytest --cov=minihass --cov-report=xml
    - name: Upload coverage reports to Codecov
      if: always()
      uses: codecov/codecov-action@v3
    - name: label when tests fail
      if: ${{ always() && (steps.pytest.outcome == 'failure' && github.event_name != 'push') }}
      run: gh issue edit "$NUMBER" --add-label "LABELS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: triage
    - name: remove label when tests succeed
      if: ${{ steps.pytest.outcome == 'failure' && github.event_name != 'push' }}
      uses: andymckay/labeler@1.0.4
      with:
        remove-labels: "test-failing"
