name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - devel

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Install Poetry
    #   uses: snok/install-poetry@v1
    #   with:
    #     virtualenvs-create: true
    #     virtualenvs-in-project: true
    - name: Install project and dependencies
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Run tests and collect coverage
      id: pytest
      run: |
        pytest --cov=minihass --cov-report=xml
    - name: Upload coverage reports to Codecov
      if: always()
      uses: codecov/codecov-action@v3
